data: 
  image_paths: /path/to/image_paths_file.npy
  image_categories: /path/to/image_categories_file.npy
  eval_base_path: /path/to/evaluation_base_folder/
  train_image_embeddings_file_path: /path/to/train_image_embeddings.npy
  caption_value_files: "/mnt/data/features/12CCM_OClipL_text_0.npy;/mnt/data/features/12CCM_OClipL_text_1.npy"
  caption_embeddings_files: "/mnt/data/features/12CCM_OClipL_text_0.npy;/mnt/data/features/12CCM_OClipL_text_1.npy"
model: SigLIP400
loss: ArcFace
train_batch_size: 128
test_batch_size: 512
base_lr: 1.0e-06
warmup_lr: 1.0e-08
min_lr: 1.0e-07
optimizer: AdamW
n_epochs: 3
weight_decay: 1.0e-2
warmup_iters: 0.0
image_size: 384
grad_norm: 1.0
n_tests_per_epoch: 200
abort_after_no_improvements: 50
gpu_id: 1